# Generated by Django 4.2.4 on 2023-08-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='authors',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='backend.author', verbose_name='Альбом'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SongInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_album', models.PositiveSmallIntegerField(verbose_name='Номер песни в альбоме')),
                ('album', models.ManyToManyField(to='backend.album', verbose_name='Альбом')),
                ('song', models.ManyToManyField(to='backend.song', verbose_name='Песня')),
            ],
        ),
    ]
