# Generated by Django 4.2.4 on 2023-08-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_song_album_remove_song_authors_album_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinalbum',
            name='album',
        ),
        migrations.AddField(
            model_name='songinalbum',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.album', verbose_name='Альбом'),
            preserve_default=False,
        ),
    ]
