# Generated by Django 4.2.4 on 2023-08-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_songinalbum_album_songinalbum_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinalbum',
            name='song',
        ),
        migrations.AddField(
            model_name='songinalbum',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.song', verbose_name='Песня'),
            preserve_default=False,
        ),
    ]
