# Generated by Django 4.2.4 on 2023-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_songinalbum_song_songinalbum_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year_of_release',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
