# Generated by Django 4.2.4 on 2023-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_album_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(related_name='songs', through='backend.SongInAlbum', to='backend.song'),
        ),
    ]
