# Generated by Django 4.2.4 on 2023-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='backend.SongsInAlbums', to='backend.song'),
        ),
    ]
